name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ctest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug

      - name: Build
        run: cmake --build build --config Debug

      - name: Test
        run: ctest --test-dir build --output-on-failure
